In [4]:
class Solution:
    def romanToInt(self, s: str) -> int:
        values = {
            "I": 1,
            "V": 5,
            "X": 10,
            "L": 50,
            "C": 100,
            "D": 500,
            "M": 1000,
        }

        total = 0
        previous = 0

        for char in reversed(s):
            current = values[char]

            if current < previous:
                total -= current
            else:
                total += current

            previous = current

        return total
    
if __name__ == "__main__":
    solution = Solution()
    s = input().split()
    print(solution.romanToInt(s[0]))
    print(solution.romanToInt("III"))  # Output: 3
    print(solution.romanToInt("LVIII"))  # Output: 58
    print(solution.romanToInt("MCMXCIV"))  # Output: 1994

6
3
58
1994


**floor**
The tool floor returns the floor of the input element-wise.
The floor of  is the largest integer  where .
```python
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.floor(my_array)         #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
```
---

**ceil**
The tool ceil returns the ceiling of the input element-wise.
The ceiling of  is the smallest integer  where .
```python
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.ceil(my_array)          #[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
```
---

**rint**
The rint tool rounds to the nearest integer of input element-wise.
```python
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.rint(my_array)          #[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
```


In [11]:
import numpy as np
np.set_printoptions(legacy='1.13')

raw = input()

arr = np.array(raw.split(), dtype=float)
print(arr)

floor = np.floor(arr)
ceil = np.ceil(arr)
rint = np.rint(arr)

print(floor)
print(ceil)
print(rint)

[ 1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


**sum**

The sum tool returns the sum of array elements over a given axis.
```python
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.sum(my_array, axis = 0)         #Output : [4 6]
print numpy.sum(my_array, axis = 1)         #Output : [3 7]
print numpy.sum(my_array, axis = None)      #Output : 10
print numpy.sum(my_array)                   #Output : 10
```
By default, the axis value is None. Therefore, it performs a sum over all the dimensions of the input array.

---

**prod**

The prod tool returns the product of array elements over a given axis.
```python
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.prod(my_array, axis = 0)            #Output : [3 8]
print numpy.prod(my_array, axis = 1)            #Output : [ 2 12]
print numpy.prod(my_array, axis = None)         #Output : 24
print numpy.prod(my_array)                      #Output : 24
```

In [1]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

n, m = map(int, input().split())

#print(n, m)

my_array = np.array([input().split() for _ in range(n)], dtype=int)

npsum = np.prod(np.sum(my_array, axis=0))
npprod = np.prod(my_array, axis=0)
npprod2 = np.prod(my_array, axis=1)
npprod3 = np.prod(my_array)
#print(f'Sum:{npsum} Prod axis 0: {npprod}, Prod: {npprod2} All Dimensions {npprod3}')
print(npsum)


27


**input()** grabs the text: It reads the very first line of the test case as a raw text string: "2 2".

**.split()** chops it up: It splits that string by the space in the middle, turning it into a list of two separate text strings: ['2', '2'].

**map()** does the conversion: Remember that factory assembly line analogy? map takes the int function and applies it to every item in that list. It turns the string '2' into the math number 2, and the second string '2' into the math number 2.

**n, m** =  unpacks the results: Because map spit out exactly two integers, Python automatically assigns the first integer to the variable n and the second integer to the variable m.

## The Three Parts of the Factory
The Conveyor Belt (The Iterable): This is your list of raw data. In our HackerRank problem, the raw data is the list of text strings we got from splitting the input: ['2', '2'].

The Tool (The Function): This is the specific machine or action you want to apply to your materials. For our code, the tool is the int function, which stamps a piece of text and turns it into a math number.

The Supervisor (map): This is the map() function itself. The supervisor doesn't do the stamping manually. Instead, you hand the supervisor the Tool and point them to the Conveyor Belt.

## How the Assembly Line Runs
When you write the code map(int, ['2', '2']), you are giving an order to the supervisor:

"Hey map, take this int tool, stand next to the conveyor belt, and use the tool on every single item that rolls by."

The supervisor then turns on the belt:

The first item '2' (text) rolls down. The supervisor uses the int tool on it. Out pops 2 (number).

The second item '2' (text) rolls down. The supervisor uses the int tool on it. Out pops 2 (number).

**map** replaces the for loop here.

In [ ]:
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.prod(my_array, axis = 0)            #Output : [3 8]
print numpy.prod(my_array, axis = 1)            #Output : [ 2 12]
print numpy.prod(my_array, axis = None)         #Output : 24
print numpy.prod(my_array)  

In [ ]:
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.sum(my_array, axis = 0)         #Output : [4 6]
print numpy.sum(my_array, axis = 1)         #Output : [3 7]
print numpy.sum(my_array, axis = None)      #Output : 10
print numpy.sum(my_array)                   #Output : 10

**min**

The tool **min** returns the minimum value along a given axis.
```python
import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.min(my_array, axis = 0)         #Output : [1 0]
print numpy.min(my_array, axis = 1)         #Output : [2 3 1 0]
print numpy.min(my_array, axis = None)      #Output : 0
print numpy.min(my_array)                   #Output : 0
```
By default, the axis value is None. Therefore, it finds the minimum over all the dimensions of the input array.

**max**

The tool **max** returns the maximum value along a given axis.
```python
import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.max(my_array, axis = 0)         #Output : [4 7]
print numpy.max(my_array, axis = 1)         #Output : [5 7 3 4]
print numpy.max(my_array, axis = None)      #Output : 7
print numpy.max(my_array)                   #Output : 7
```
By default, the axis value is None. Therefore, it finds the maximum over all the dimensions of the input array.

In [ ]:
# Find min of axis 1 and then find the max of that axis.
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

n, m = map(int, input().split())

#print(n, m)

my_array = np.array([input().split() for _ in range(n)], dtype=int)

npsum = np.max(np.min(my_array, axis=1))

print(npsum)


**mean**

The **mean** tool computes the arithmetic mean along the specified axis.
```python
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.mean(my_array, axis = 0)        #Output : [ 2.  3.]
print numpy.mean(my_array, axis = 1)        #Output : [ 1.5  3.5]
print numpy.mean(my_array, axis = None)     #Output : 2.5
print numpy.mean(my_array)                  #Output : 2.5
```
By default, the axis is None. Therefore, it computes the mean of the flattened array.

---
**var**

The **var** tool computes the arithmetic variance along the specified axis.
```python
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.var(my_array, axis = 0)         #Output : [ 1.  1.]
print numpy.var(my_array, axis = 1)         #Output : [ 0.25  0.25]
print numpy.var(my_array, axis = None)      #Output : 1.25
print numpy.var(my_array)                   #Output : 1.25
```
By default, the axis is None. Therefore, it computes the variance of the flattened array.

---
**std**

The **std** tool computes the arithmetic standard deviation along the specified axis.
```python
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.std(my_array, axis = 0)         #Output : [ 1.  1.]
print numpy.std(my_array, axis = 1)         #Output : [ 0.5  0.5]
print numpy.std(my_array, axis = None)      #Output : 1.11803398875
print numpy.std(my_array)                   #Output : 1.11803398875
```
By default, the axis is None. Therefore, it computes the standard deviation of the flattened array.

Task

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

n, m = map(int, input().split())

my_array = np.array([input().split() for _ in range(n)], dtype=int)


npmean = np.mean(my_array, axis=1)
npvar = np.var(my_array, axis=0)
npstd = np.std(my_array)

print(npmean)
print(npvar)
if npstd == 0.0:
    print(f'{npstd:.1f}')
else:
    print(f'{npstd:.11f}')

"""Weird because of formatting requirements.  Rank Python 119230"""

**dot**

The **dot** tool returns the dot product of two arrays.
```pythomn
import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print numpy.dot(A, B)       #Output : 11
```
---
**cross**

The **cross** tool returns the cross product of two arrays.
```python
import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print numpy.cross(A, B)     #Output : -2
```

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

rows = int(input().strip())
# Explanation: We read the number of rows from input and then create a 
# list of lists (matrix) by reading each row of input and converting 
# it to a list of integers. We then convert this list of lists into a 
# NumPy array for easier manipulation. We extract the first two rows 
# as vectors A and B, compute their dot product and cross product, 
# and print the results. Finally, we read another set of input to 
# create a new array and print it.
matrix: list[list[int]] = [list(map(int, input().split())) for _ in range(rows)]

matrix_np = np.array(matrix, dtype=int)

A = matrix_np[0]  # length 3
B = matrix_np[1]  # length 3

print(np.dot(A, B))
print(np.cross(A, B))

my_array = map( int, np.array([input().split() for _ in range(n)], dtype=int))

print(my_array)




ValueError: invalid literal for int() with base 10: '2 1 2 3 4 1 2 3 4'