In [4]:
class Solution:
    def romanToInt(self, s: str) -> int:
        values = {
            "I": 1,
            "V": 5,
            "X": 10,
            "L": 50,
            "C": 100,
            "D": 500,
            "M": 1000,
        }

        total = 0
        previous = 0

        for char in reversed(s):
            current = values[char]

            if current < previous:
                total -= current
            else:
                total += current

            previous = current

        return total
    
if __name__ == "__main__":
    solution = Solution()
    s = input().split()
    print(solution.romanToInt(s[0]))
    print(solution.romanToInt("III"))  # Output: 3
    print(solution.romanToInt("LVIII"))  # Output: 58
    print(solution.romanToInt("MCMXCIV"))  # Output: 1994

6
3
58
1994


**floor**
The tool floor returns the floor of the input element-wise.
The floor of  is the largest integer  where .
```python
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.floor(my_array)         #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
```
**ceil**
The tool ceil returns the ceiling of the input element-wise.
The ceiling of  is the smallest integer  where .
```python
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.ceil(my_array)          #[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
```
**rint**
The rint tool rounds to the nearest integer of input element-wise.
```python
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.rint(my_array)          #[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
```


In [11]:
import numpy as np
np.set_printoptions(legacy='1.13')

raw = input()

arr = np.array(raw.split(), dtype=float)
print(arr)

floor = np.floor(arr)
ceil = np.ceil(arr)
rint = np.rint(arr)

print(floor)
print(ceil)
print(rint)

[ 1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
