In [2]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
# pick the max from each line and then output the formula
# 3 1000 is K M K lines
# a**2, b**2, c**2 % 1000


first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

arr = []
total = 0
for i in range(n):
    
    k = input().rstrip().split()
    
    arr.append(k)
    mapped_result =[int(x) for x in k]
    
    first_max = max(mapped_result)
    first_sq = first_max ** 2
    
    total += first_sq
    
print(total)


681809971182592


7 867
7 6429964 4173738 9941618 2744666 5392018 5813128 9452095
7 6517823 4135421 6418713 9924958 9370532 7940650 2027017
7 1506500 3460933 1550284 3679489 4538773 5216621 5645660
7 7443563 5181142 8804416 8726696 5358847 7155276 4433125
7 2230555 3920370 7851992 1176871 610460 309961 3921536
7 8518829 8639441 3373630 5036651 5291213 2308694 7477960
7 7178097 249343 9504976 8684596 6226627 1055259 4880436

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
# pick the max from each line and then output the formula
# 3 1000 is K M K lines
# a**2, b**2, c**2 % 1000
import itertools

maps_result = """7 867
                7 6429964 4173738 9941618 2744666 5392018 5813128 9452095
                7 6517823 4135421 6418713 9924958 9370532 7940650 2027017
                7 1506500 3460933 1550284 3679489 4538773 5216621 5645660
                7 7443563 5181142 8804416 8726696 5358847 7155276 4433125
                7 2230555 3920370 7851992 1176871 610460 309961 3921536
                7 8518829 8639441 3373630 5036651 5291213 2308694 7477960
                7 7178097 249343 9504976 8684596 6226627 1055259 4880436"""

first_multiple_input = maps_result.rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

arr = []

mtotal = 0


for i in range(n):
    k = maps_result.rstrip().split()
    string_lst = [char for char in str(k[1:])]
    
    mapped_results =[int(x) for x in k[1:]]
    arr.append(mapped_results)
    
    
    # mapped_result prints the integers for that line
    # now I need to split them
    
max_val = 0   
for combo in itertools.product(*arr):
    # cannot square a tuple
    val = sum(x**2 for x in combo) % m
    if val > max_val:
        max_val = val
    
print(max_val)

reachable = {0}                    # before any list, the sum is 0
for lst in arr:
    reachable = {(r + x * x) % m   # add this list's contribution...
                 for r in reachable # ...to every residue we can already reach...
                 for x in lst}      # ...for every choice in this list
print(max(reachable))



KeyboardInterrupt: 

## Working Hackerrank problem is much easier but some troubles where with the loops and such.
*-splat - unpacking operator in python - wildcard
(*matrix) means every combination

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
# pick the max from each line and then output the formula
# 3 1000 is K M K lines
# a**2, b**2, c**2 % 1000
import itertools
from itertools import product

first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

arr = []

mtotal = 0



for i in range(n):
    
    k = input().rstrip().split()
    string_lst = [char for char in str(k[1:])]
    
    mapped_results =[int(x) for x in k[1:]]
    arr.append(mapped_results)
    
    
    # mapped_result prints the integers for that line
    # now I need to split them
    
max_val = 0   
for combo in product(*arr):
    # cannot square a tuple
    val = sum(x**2 for x in combo) % m
    if val > max_val:
        max_val = val
    
print(max_val)


## Yield 
Yield saves the local state and returns a value

## map() vs starmap()
its similar to how function(a, b) and function(*c) works.

* - python unpacking operator

Standard **map()** expects you to pass in separate iterables for every arguement.  It then pulls one item from each iterable simulataneously to feed the function.
*   Data structure: Separate lists/iterables.
*   How it executes: pow(2, 5), then pow(3, 2)

**starmap()** Already pre-zipped or grouped into single iterable of tuples, takes a tuple and uses * operator to unpack the tuple into function arguments
*   Data structure: A single list of tuples (or other iterables).
*   How it executes: pow(*(2, 5)), then pow(*(3, 2))


```python
bases = [2, 3, 10]
exponents = [5, 2, 3]

# map takes an item from 'bases' and an item from 'exponents'
results = list(map(pow, bases, exponents))
# Output: [32, 9, 1000]
```

```python
import itertools

paired_data = [(2, 5), (3, 2), (10, 3)]

# starmap takes one tuple at a time and unpacks it: pow(*tuple)
results = list(itertools.starmap(pow, paired_data))
# Output: [32, 9, 1000]
```

In [1]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import itertools

from itertools import combinations

raw = input().rstrip().split()

k = int(raw[1])
arr = sorted(raw[0])

max_size = k


for size in range(1, max_size + 1):
    for combo in combinations(arr, size):
        new_combo = "".join(combo)
        print(new_combo)
"""        
all_combos = itertools.chain.from_iterable(
    itertools.combinations(arr, r) for r in range(1, max_size + 1)
)
for combo2 in all_combos:
    print(combo2)
"""

A
C
H
K
AC
AH
AK
CH
CK
HK


'        \nall_combos = itertools.chain.from_iterable(\n    itertools.combinations(arr, r) for r in range(1, max_size + 1)\n)\nfor combo2 in all_combos:\n    print(combo2)\n'

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import itertools

from itertools import combinations_with_replacement

raw = input().rstrip().split()

k = int(raw[1])
arr = sorted(raw[0])

max_size = k

for size in range(k, max_size + 1):
    for combo in combinations_with_replacement(arr, size):
        new_combo = "".join(combo)
        print(new_combo)

AAA
AAC
AAE
AAH
AAK
AAR
ACC
ACE
ACH
ACK
ACR
AEE
AEH
AEK
AER
AHH
AHK
AHR
AKK
AKR
ARR
CCC
CCE
CCH
CCK
CCR
CEE
CEH
CEK
CER
CHH
CHK
CHR
CKK
CKR
CRR
EEE
EEH
EEK
EER
EHH
EHK
EHR
EKK
EKR
ERR
HHH
HHK
HHR
HKK
HKR
HRR
KKK
KKR
KRR
RRR


In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from itertools import groupby

raw = input().rstrip().split()

# [k for k, g in groupby('AAAABBBCCDAABBB')] --> A B C D A B
# [list(g) for k, g in groupby('AAAABBBCCD')] --> AAAA BBB CC D

data = raw

groups = []
uniquekeys = []


for k, g in groupby(data):
    k, g = set(k), list(g)
    print(k, g)
    groups = str(g)
    count = 0

    for i in range(len(groups) - 1):
        
        if groups[i] != groups[i+1]:

            uniquekeys = sum(1 for x in groups[:i+1] if x == groups[i])
            if str(uniquekeys).isnumeric() and str(groups[i]).isnumeric():
                print(f"({uniquekeys}, {groups[i]})", end=' ')
        

                

"""   
# Sample Input: 1222311
# Sample Output: (1, 1) (3, 2) (1, 3) (2, 1)

# Essentially we want to count the number of times each character
# appears in the string and then output the character and its 
# count. The groupby function from itertools can be used to group 
# consecutive characters together, and we can use a lambda function 
# as the key to sort the data before grouping. The output will be 
# a list of tuples, where each tuple contains a unique character
# and its count.

Explanation

First, the character 1 occurs only once. It is replaced by (1, 1). 
Then the character 2 occurs three times, and it is replaced by (3, 2) and so on.

Also, note the single space within each compression and between 
the compressions.
"""

{'3', '2', '1'} ['1222311']
(1, 1) (1, 2) (2, 2) (3, 2) (1, 3) (2, 1) (3, 1) 

'   \n# Sample Input: 1222311\n# Sample Output: (1, 1) (3, 2) (1, 3) (2, 1)\n\n# Essentially we want to count the number of times each character\n# appears in the string and then output the character and its \n# count. The groupby function from itertools can be used to group \n# consecutive characters together, and we can use a lambda function \n# as the key to sort the data before grouping. The output will be \n# a list of tuples, where each tuple contains a unique character\n# and its count.\n\nExplanation\n\nFirst, the character 1 occurs only once. It is replaced by (1, 1). \nThen the character 2 occurs three times, and it is replaced by (3, 2) and so on.\n\nAlso, note the single space within each compression and between \nthe compressions.\n'

## groupby() - How groupby Already Resets Everything
When you write for k, g in groupby(data):, Python takes your string '1222311' and chops it into completely separate, fresh lists every time the character changes.

If you just look at list(g) inside the loop, here is exactly what it contains on each pass:

Pass 1: ['1'] (It isolated the first '1')

Pass 2: ['2', '2', '2'] (It isolated the '2's)

Pass 3: ['3'] (It isolated the '3')

Pass 4: ['1', '1'] (It isolated the final '1's into a brand-new, reset list)

Notice how Pass 4 is just ['1', '1']? It doesn't remember the first '1' from Pass 1 at all. It is a completely fresh block.

The Built-in Solution: len()
Because list(g) is already a perfectly isolated list of just the current consecutive characters, you don't need a for loop to count them. You don't need sum() or if statements.

You just need to ask Python: "How many items are in this list?"

The function for that is len().

len(['2', '2', '2']) is 3.

len(['1', '1']) is 2.

In [96]:
from itertools import groupby

data = input()

for k, g in groupby(data):
    # 1. Turn the group 'g' into a list so you can measure it
    group_list = list(g)
    
    # 2. Get the count simply by measuring the length of that list
    count = len(group_list)
    
    # 3. Print the count and the key 'k' in the format HackerRank wants
    # (Remember k is currently a string, so you might need to convert it to an int for the output!)
    print(f"({count}, {k})", end=' ')

(1, 1) (3, 2) (1, 3) (2, 1) 

In [ ]:
# What are the odds of selecting 'a' out of K indices,
# 4 - size of list - len(N)
# a a c d
# 2
# So out of K indices, how many times would they pick a, 
# with a list sized len(N)
from itertools import combinations

raw = """4
a a c d
2"""
#print(raw)
raw = raw.splitlines()
#print(raw)
raw = [line.strip() for line in raw]
#print(raw)

k = int(raw[2])
arr = sorted(raw[1].split())
max_size = k
length = int(raw[0])
letter = 'a'
count = 0.0
total = 0.0
for size in range(k, max_size + 1):
    for combo in combinations(arr, size):
        new_combo = "".join(combo)
        #print(new_combo)
        total += 1
        if new_combo.count(letter) > 0:
            count += 1

new_total = count / total
print(f"{new_total:.4f}")


#combinations_arr = list(combinations(arr, k))
#print(combinations_arr)


"""
Sample input:

4
a a c d
2

Sample Output:

0.8333

Explanation

All possible combinations of 2 indices are:
(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)

Out of these 6 combinations, 5 of them contain either index 1 or index 2 which are the indices that contain the letter 'a'.

Hence, the answer is 5/6 = 0.8333
"""


"\nSample input:\n\n4\na a c d\n2\n\nSample Output:\n\n0.8333\n\nExplanation\n\nAll possible combinations of 2 indices are:\n(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)\n\nOut of these 6 combinations, 5 of them contain either index 1 or index 2 which are the indices that contain the letter 'a'.\n\nHence, the answer is 5/6 = 0.8333\n"

In [ ]:
from itertools import combinations

length = int(input())

# Grab Second line
arr = input().split()

# Third line
k = int(input())

max_size = k

letter = 'a'
count = 0.0
total = 0.0
for size in range(k, max_size + 1):
    for combo in combinations(arr, size):
        new_combo = "".join(combo)
        #print(new_combo)
        total += 1
        if new_combo.count(letter) > 0:
            count += 1

new_total = count / total
print(f"{new_total:.4f}")

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

raw = input().rstrip().split()

n = int(raw[0])
m = int(raw[1])

# For multiple lines to read
raw_A = [input().split() for _ in range(n)]
raw_B = [input().split() for _ in range(n)]

# Convert to np.array
arr_A = np.array([raw_A], dtype=int)
arr_B = np.array([raw_B], dtype=int)
#print(arr_A)
#print(arr_B)

# now you can use np.add if you did not convert, because
# I converted, printing is the same.
numpy_add = np.add(arr_A, arr_B)
print(arr_A + arr_B)
numpy_sub = np.subtract(arr_A, arr_B)
print(arr_A - arr_B)
numpy_mult = np.multiply(arr_A, arr_B)
print(arr_A * arr_B)
numpy_div = np.divide(arr_A, arr_B)
print(arr_A // arr_B)
numpy_mod = np.mod(arr_A, arr_B)
print(arr_A % arr_B)
numpy_pow = np.power(arr_A, arr_B)
print(arr_A ** arr_B)

[[2. 4. 6. 8.]]
[[0. 0. 0. 0.]]
[[ 1.  4.  9. 16.]]
[[1. 1. 1. 1.]]
[[0. 0. 0. 0.]]
[[  1.   4.  27. 256.]]


## Numpy Arrays

Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )

```python
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print a + b                     #[  6.   8.  10.  12.]
print numpy.add(a, b)           #[  6.   8.  10.  12.]

print a - b                     #[-4. -4. -4. -4.]
print numpy.subtract(a, b)      #[-4. -4. -4. -4.]

print a * b                     #[  5.  12.  21.  32.]
print numpy.multiply(a, b)      #[  5.  12.  21.  32.]

print a / b                     #[ 0.2         0.33333333  0.42857143  0.5       ]
print numpy.divide(a, b)        #[ 0.2         0.33333333  0.42857143  0.5       ]

print a % b                     #[ 1.  2.  3.  4.]
print numpy.mod(a, b)           #[ 1.  2.  3.  4.]

print a**b                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
print numpy.power(a, b)         #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
```

If you need to combine multiple into one array

```python
raw_A = [input().split() for _ in range(n)]
raw_B = [input().split() for _ in range(n)]

arr_A = np.array([raw_A], dtype=int)
arr_B = np.array([raw_B], dtype=int)
```